"""
osint_raw_data.py
=================
Generates realistic sample records (8 rows per source) representing
actual data that would be fetched from each OSINT channel.
Imported by opensource.py for the "Raw OSINT Sources" tab.
"""

from datetime import datetime, timedelta
import random

random.seed(99)


def _date(days_back):
    return (datetime.today() - timedelta(days=days_back)).strftime("%d %b %Y")


# ─────────────────────────────────────────────────────────────────────────────
# 1. TWITTER / X  SOCIAL
# ─────────────────────────────────────────────────────────────────────────────
TWITTER_SAMPLES = [
    {
        "Handle":    "@surat_nagrik",
        "Tweet":     "3 din thi pani nathi aavtu amara vistaar ma. @SuratMunicipal @CMOGuj please urgent action lo! #WaterCrisis #Surat",
        "District":  "Surat",
        "Category":  "💧 Water Supply",
        "Sentiment": "😠 Negative",
        "Likes":     312,
        "Retweets":  87,
        "Date":      _date(1),
    },
    {
        "Handle":    "@rajkot_roads",
        "Tweet":     "The pothole on Kalawad Road has been there for 2 months! Two-wheeler accidents happening daily. @RajkotMunicipal wake up! #PotholeProblems",
        "District":  "Rajkot",
        "Category":  "🏗️ Roads & Infrastructure",
        "Sentiment": "😠 Negative",
        "Likes":     524,
        "Retweets":  203,
        "Date":      _date(2),
    },
    {
        "Handle":    "@ahmd_bijli",
        "Tweet":     "Varsad ma light nathi aavti 6 kalaak thi. PGVCL no jawab nathi malto. #PowerCut #Ahmedabad aakaash medha chhe ane light bandh chhe",
        "District":  "Ahmedabad",
        "Category":  "⚡ Electricity",
        "Sentiment": "😠 Negative",
        "Likes":     198,
        "Retweets":  44,
        "Date":      _date(1),
    },
    {
        "Handle":    "@gandhinagar_rtd",
        "Tweet":     "New AIIMS Gandhinagar has improved healthcare in the region significantly. Great initiative by Gujarat Govt! #Gujarat #Healthcare #Development",
        "District":  "Gandhinagar",
        "Category":  "🏥 Healthcare",
        "Sentiment": "😊 Positive",
        "Likes":     1_240,
        "Retweets":  380,
        "Date":      _date(3),
    },
    {
        "Handle":    "@morbi_concerned",
        "Tweet":     "Garbage collection has stopped for 10 days in Morbi. Mosquito breeding happening everywhere. Health hazard! @MorbiNagarpalika",
        "District":  "Morbi",
        "Category":  "🗑️ Sanitation & Waste",
        "Sentiment": "😠 Negative",
        "Likes":     421,
        "Retweets":  156,
        "Date":      _date(2),
    },
    {
        "Handle":    "@kutch_farmer",
        "Tweet":     "Kharif season support excellent this year. PM Kisan Samman funds deposited on time. Salute to the officers! #Agriculture #Gujarat #Kutch",
        "District":  "Kutch",
        "Category":  "🌾 Agriculture",
        "Sentiment": "😊 Positive",
        "Likes":     867,
        "Retweets":  234,
        "Date":      _date(4),
    },
    {
        "Handle":    "@vadodara_rti",
        "Tweet":     "Filed RTI 6 months back about land record correction in Vadodara taluka. No response till date. CIC ki kya jaroorat hai! #RTI #LandRecord",
        "District":  "Vadodara",
        "Category":  "📋 Land & Revenue",
        "Sentiment": "😠 Negative",
        "Likes":     290,
        "Retweets":  112,
        "Date":      _date(5),
    },
    {
        "Handle":    "@bhavnagar_edu",
        "Tweet":     "Teacher missing from govt primary school in Bhavnagar for 3 months. 60 students with no teacher! @GujEduDept #EducationCrisis #Gujarat",
        "District":  "Bhavnagar",
        "Category":  "📚 Education",
        "Sentiment": "😠 Negative",
        "Likes":     735,
        "Retweets":  291,
        "Date":      _date(3),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# 2. PG PORTAL  (pgportal.gov.in — Public Grievance Portal)
# ─────────────────────────────────────────────────────────────────────────────
PGPORTAL_SAMPLES = [
    {
        "Grievance ID":  "GUJTW2026051823",
        "Complainant":   "Rameshbhai Patel",
        "Department":    "Municipal Corp. – Water Dept",
        "Description":   "Water supply to Ward 14, Surat has been completely disrupted for 5 days. Residents are forced to buy water tankers at high cost.",
        "District":      "Surat",
        "Category":      "💧 Water Supply",
        "Filed Date":    _date(6),
        "Status":        "🟡 Under Process",
        "Priority":      "High",
    },
    {
        "Grievance ID":  "GUJPWD2026051491",
        "Complainant":   "Fatimaben Shaikh",
        "Department":    "PWD – Roads Division",
        "Description":   "National Highway 27 stretch near Anand bypass has massive potholes causing accidents. Two accidents reported in last week alone.",
        "District":      "Anand",
        "Category":      "🏗️ Roads & Infrastructure",
        "Filed Date":    _date(9),
        "Status":        "🔴 Pending",
        "Priority":      "Critical",
    },
    {
        "Grievance ID":  "GUJPGV2026050892",
        "Complainant":   "Jayeshkumar Mehta",
        "Department":    "PGVCL – Electricity",
        "Description":   "Transformer in village Mota Mauliya, Banaskantha has been defunct for 8 days. Entire village without electricity. Crops at risk.",
        "District":      "Banaskantha",
        "Category":      "⚡ Electricity",
        "Filed Date":    _date(11),
        "Status":        "✅ Resolved",
        "Priority":      "Critical",
    },
    {
        "Grievance ID":  "GUJHLT2026051107",
        "Complainant":   "Savitaben Rathod",
        "Department":    "Health Dept – PHC Division",
        "Description":   "PHC at Dhanpur, Dang does not have doctor since 3 months. Tribal patients traveling 40 km to Ahwa for basic treatment.",
        "District":      "Dang",
        "Category":      "🏥 Healthcare",
        "Filed Date":    _date(14),
        "Status":        "🟡 Under Process",
        "Priority":      "High",
    },
    {
        "Grievance ID":  "GUJFCS2026051654",
        "Complainant":   "Dhirubhai Solanki",
        "Department":    "Food & Civil Supplies",
        "Description":   "Ration card updated but dealer refuses to provide subsidized ration in Patan. Demands Rs.200 extra per month illegally.",
        "District":      "Patan",
        "Category":      "🛒 Ration & PDS",
        "Filed Date":    _date(7),
        "Status":        "🟠 Forwarded",
        "Priority":      "Medium",
    },
    {
        "Grievance ID":  "GUJRVN2026051332",
        "Complainant":   "Nareshkumar Thakor",
        "Department":    "Revenue – Mamlatdar Office",
        "Description":   "Land mutation pending since 2 years for agricultural land in Sabarkantha. Fees paid multiple times but no action.",
        "District":      "Sabarkantha",
        "Category":      "📋 Land & Revenue",
        "Filed Date":    _date(20),
        "Status":        "🔴 Pending",
        "Priority":      "High",
    },
    {
        "Grievance ID":  "GUJEMR2026051780",
        "Complainant":   "Kantilal Vasava",
        "Department":    "Rural Development – MGNREGA",
        "Description":   "MGNREGA wages not paid for 3 months in Chhota Udaipur block. 340 workers affected. Contractor taking cut from payments.",
        "District":      "Chhota Udaipur",
        "Category":      "👷 Employment/MGNREGA",
        "Filed Date":    _date(5),
        "Status":        "🟡 Under Process",
        "Priority":      "Critical",
    },
    {
        "Grievance ID":  "GUJPOL2026051095",
        "Complainant":   "Meenaben Chauhan",
        "Department":    "Home Dept – Police",
        "Description":   "Repeated chain-snatching incidents in Kalupur area, Ahmedabad. Police not registering FIR. Criminals known to locals.",
        "District":      "Ahmedabad",
        "Category":      "⚖️ Law & Order",
        "Filed Date":    _date(8),
        "Status":        "🟡 Under Process",
        "Priority":      "High",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# 3. MYGOV PORTAL  (mygov.in citizen feedback)
# ─────────────────────────────────────────────────────────────────────────────
MYGOV_SAMPLES = [
    {
        "Feedback ID":   "MG-GUJ-2026-88421",
        "Citizen":       "Priyanka Shah",
        "District":      "Gandhinagar",
        "Category":      "🏥 Healthcare",
        "Suggestion":    "Ayushman Bharat card should be accepted at ALL private hospitals in Gujarat, not just empanelled ones. Many rural hospitals still reject it.",
        "Status":        "✅ Acknowledged",
        "Upvotes":       1_842,
        "Date":          _date(4),
    },
    {
        "Feedback ID":   "MG-GUJ-2026-91034",
        "Citizen":       "Alpesh Trivedi",
        "District":      "Ahmedabad",
        "Category":      "🏗️ Roads & Infrastructure",
        "Suggestion":    "BRTS network should be extended to Bopal and Prahlad Nagar areas. Metro Phase 2 is taking too long. Residents depend on overcrowded buses.",
        "Status":        "🟡 Under Review",
        "Upvotes":       3_201,
        "Date":          _date(6),
    },
    {
        "Feedback ID":   "MG-GUJ-2026-87654",
        "Citizen":       "Nisha Parmar",
        "District":      "Vadodara",
        "Category":      "📚 Education",
        "Suggestion":    "Skill development centers under PMKVY scheme in Vadodara need better equipment. Computers are 10 years old. Youth not getting industry-ready skills.",
        "Status":        "🟡 Under Review",
        "Upvotes":       924,
        "Date":          _date(9),
    },
    {
        "Feedback ID":   "MG-GUJ-2026-93210",
        "Citizen":       "Ravi Joshi",
        "District":      "Rajkot",
        "Category":      "💧 Water Supply",
        "Suggestion":    "Smart water meters being installed in Rajkot are excellent! Request to fast-track the project to all 150 wards before monsoon. Saves water and money.",
        "Status":        "✅ Implemented",
        "Upvotes":       2_450,
        "Date":          _date(12),
    },
    {
        "Feedback ID":   "MG-GUJ-2026-86199",
        "Citizen":       "Surekha Desai",
        "District":      "Surat",
        "Category":      "🗑️ Sanitation & Waste",
        "Suggestion":    "Door-to-door garbage collection timings need to be fixed and communicated to residents via SMS. Workers come at different times every day causing inconvenience.",
        "Status":        "✅ Acknowledged",
        "Upvotes":       1_120,
        "Date":          _date(8),
    },
    {
        "Feedback ID":   "MG-GUJ-2026-94580",
        "Citizen":       "Hitesh Patel",
        "District":      "Anand",
        "Category":      "🌾 Agriculture",
        "Suggestion":    "Soil health card scheme is excellent. But results should be delivered via WhatsApp, not only physical card. Farmers lose the card. Digital copy is the need.",
        "Status":        "✅ Implemented",
        "Upvotes":       3_876,
        "Date":          _date(15),
    },
    {
        "Feedback ID":   "MG-GUJ-2026-89023",
        "Citizen":       "Komal Bhatt",
        "District":      "Mehsana",
        "Category":      "⚡ Electricity",
        "Suggestion":    "Solar rooftop subsidy under PM Surya Ghar scheme in Mehsana is excellent. Process should be made faster - currently takes 4 months for installation.",
        "Status":        "🟡 Under Review",
        "Upvotes":       1_654,
        "Date":          _date(7),
    },
    {
        "Feedback ID":   "MG-GUJ-2026-91877",
        "Citizen":       "Mukesh Rana",
        "District":      "Junagadh",
        "Category":      "👷 Employment/MGNREGA",
        "Suggestion":    "MGNREGA job card renewal process is too complicated. Online portal crashes. Village level facilitators needed to help illiterate beneficiaries.",
        "Status":        "🟡 Under Review",
        "Upvotes":       786,
        "Date":          _date(11),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# 4. NEWS ARTICLES  (Divya Bhaskar, Sandesh, TOI Gujarat, Navbharat Times)
# ─────────────────────────────────────────────────────────────────────────────
NEWS_SAMPLES = [
    {
        "Headline":     "Surat: 5 wards face acute water crisis, residents demand urgent action from SMC",
        "Publication":  "Divya Bhaskar",
        "Language":     "Gujarati",
        "District":     "Surat",
        "Category":     "💧 Water Supply",
        "Sentiment":    "😠 Negative",
        "Date":         _date(2),
        "Source URL":   "divyabhaskar.co.in/surat-water-crisis-2026",
    },
    {
        "Headline":     "Gujarat govt unveils Rs 2,400 crore road repair package for monsoon 2026",
        "Publication":  "Times of India – Ahmedabad",
        "Language":     "English",
        "District":     "State-wide",
        "Category":     "🏗️ Roads & Infrastructure",
        "Sentiment":    "😊 Positive",
        "Date":         _date(5),
        "Source URL":   "timesofindia.com/gujarat-road-repair-2026",
    },
    {
        "Headline":     "PGVCL transformer failures in Banaskantha villages: 18 settlements in dark",
        "Publication":  "Sandesh",
        "Language":     "Gujarati",
        "District":     "Banaskantha",
        "Category":     "⚡ Electricity",
        "Sentiment":    "😠 Negative",
        "Date":         _date(3),
        "Source URL":   "sandesh.com/banaskantha-power-crisis",
    },
    {
        "Headline":     "Morbi district receives 5 new 108 ambulances; remote tribal areas to benefit",
        "Publication":  "Gujarat Samachar",
        "Language":     "Gujarati",
        "District":     "Morbi",
        "Category":     "🏥 Healthcare",
        "Sentiment":    "😊 Positive",
        "Date":         _date(7),
        "Source URL":   "gujaratsamachar.com/morbi-ambulance-2026",
    },
    {
        "Headline":     "RTI reveals: 42% of MGNREGA payments delayed beyond 15 days in Dahod district",
        "Publication":  "The Wire – India",
        "Language":     "English",
        "District":     "Dahod",
        "Category":     "👷 Employment/MGNREGA",
        "Sentiment":    "😠 Negative",
        "Date":         _date(8),
        "Source URL":   "thewire.in/dahod-mgnrega-delay-rti",
    },
    {
        "Headline":     "Kutch farmers get record Rs 1,250 crore crop insurance payout for 2025 kharif",
        "Publication":  "Financial Express – Gujarat",
        "Language":     "English",
        "District":     "Kutch",
        "Category":     "🌾 Agriculture",
        "Sentiment":    "😊 Positive",
        "Date":         _date(10),
        "Source URL":   "financialexpress.com/kutch-crop-insurance",
    },
    {
        "Headline":     "Corruption expose: Navsari ration shop owner arrested for diverting subsidized rice",
        "Publication":  "Navbharat Times – Surat",
        "Language":     "Hindi",
        "District":     "Navsari",
        "Category":     "💰 Corruption/Bribery",
        "Sentiment":    "😠 Negative",
        "Date":         _date(4),
        "Source URL":   "navbharattimes.com/navsari-ration-corruption",
    },
    {
        "Headline":     "Panchmahal school dropout rate falls to 4.2%: best in 10 years, says govt report",
        "Publication":  "Indian Express – Ahmedabad",
        "Language":     "English",
        "District":     "Panchmahal",
        "Category":     "📚 Education",
        "Sentiment":    "😊 Positive",
        "Date":         _date(13),
        "Source URL":   "indianexpress.com/panchmahal-edu-report-2026",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# 5. RTI FILINGS  (Right to Information Act applications)
# ─────────────────────────────────────────────────────────────────────────────
RTI_SAMPLES = [
    {
        "RTI Number":   "RTI/GUJ/WATER/2026/04821",
        "Filed By":     "Ramanlal Desai",
        "Department":   "Gujarat Water Supply & Sewerage Board",
        "Query Subject": "Details of contractors awarded pipeline repair work in Ahmedabad North zone and actual vs billed work done",
        "District":     "Ahmedabad",
        "Category":     "💧 Water Supply",
        "Filed Date":   _date(30),
        "Response Due": _date(-30),
        "Status":       "🔴 No Response",
    },
    {
        "RTI Number":   "RTI/GUJ/PWD/2026/03654",
        "Filed By":     "Jignesh Acharya",
        "Department":   "PWD – Gujarat Roads Division",
        "Query Subject": "Total amount spent on Rajkot bypass road repair in 2025-26 and list of contractors with tender documents",
        "District":     "Rajkot",
        "Category":     "🏗️ Roads & Infrastructure",
        "Filed Date":   _date(25),
        "Response Due": _date(-5),
        "Status":       "🟡 Partial Response",
    },
    {
        "RTI Number":   "RTI/GUJ/HLTH/2026/05102",
        "Filed By":     "Geeta Vasava",
        "Department":   "Health & Family Welfare – Gujarat",
        "Query Subject": "Number of doctor vacancies in tribal district PHCs (Dang, Tapi, Narmada) and recruitment timeline",
        "District":     "Dang",
        "Category":     "🏥 Healthcare",
        "Filed Date":   _date(18),
        "Response Due": _date(12),
        "Status":       "🟡 Under Process",
    },
    {
        "RTI Number":   "RTI/GUJ/MGNG/2026/02987",
        "Filed By":     "Babubhai Rathwa",
        "Department":   "Rural Development – MGNREGA Division",
        "Query Subject": "Job card holder count, work allotted vs work completed, payment disbursed in Chhota Udaipur block FY 2025-26",
        "District":     "Chhota Udaipur",
        "Category":     "👷 Employment/MGNREGA",
        "Filed Date":   _date(22),
        "Response Due": _date(8),
        "Status":       "✅ Responded",
    },
    {
        "RTI Number":   "RTI/GUJ/EDUC/2026/04456",
        "Filed By":     "Varsha Pandya",
        "Department":   "Education Dept – Gujarat",
        "Query Subject": "Names and attendance records of teachers in 3 govt primary schools in Amreli where students reported no teacher for months",
        "District":     "Amreli",
        "Category":     "📚 Education",
        "Filed Date":   _date(40),
        "Response Due": _date(-10),
        "Status":       "🔴 Rejected (Sec 8)",
    },
    {
        "RTI Number":   "RTI/GUJ/RCVN/2026/03219",
        "Filed By":     "Mukesh Prajapati",
        "Department":   "Revenue Department – Gujarat",
        "Query Subject": "Status of pending land mutation cases in Mehsana district – cases older than 1 year and reasons for delay",
        "District":     "Mehsana",
        "Category":     "📋 Land & Revenue",
        "Filed Date":   _date(35),
        "Response Due": _date(-5),
        "Status":       "🟡 Partial Response",
    },
    {
        "RTI Number":   "RTI/GUJ/FCS/2026/05788",
        "Filed By":     "Laxmiben Solanki",
        "Department":   "Food & Civil Supplies – Gujarat",
        "Query Subject": "Number of ration shops cancelled/penalized for malpractice in Patan and Banaskantha districts in 2024-25",
        "District":     "Patan",
        "Category":     "🛒 Ration & PDS",
        "Filed Date":   _date(12),
        "Response Due": _date(18),
        "Status":       "🟡 Under Process",
    },
    {
        "RTI Number":   "RTI/GUJ/POLL/2026/04033",
        "Filed By":     "Hareshbhai Jadav",
        "Department":   "Home Department – Gujarat Police",
        "Query Subject": "FIR registration statistics for chain-snatching and street crime in Kalupur, Dariapur areas Ahmedabad Jan-Apr 2026",
        "District":     "Ahmedabad",
        "Category":     "⚖️ Law & Order",
        "Filed Date":   _date(28),
        "Response Due": _date(2),
        "Status":       "✅ Responded",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# 6. REDDIT / FORUMS  (r/gujarat, r/india, r/ahmedabad)
# ─────────────────────────────────────────────────────────────────────────────
REDDIT_SAMPLES = [
    {
        "Post Title":   "Surat water supply completely broken in VIP Road area - anyone else?",
        "Subreddit":    "r/surat",
        "Posted By":    "u/surat_frustrated_21",
        "District":     "Surat",
        "Category":     "💧 Water Supply",
        "Score":        847,
        "Comments":     134,
        "Sentiment":    "😠 Negative",
        "Top Comment":  "This is happening every year before monsoon. SMCL never preps the infrastructure.",
        "Date":         _date(3),
    },
    {
        "Post Title":   "Comprehensive guide: How to file complaint on PG Portal for road issues in Gujarat [with screenshots]",
        "Subreddit":    "r/gujarat",
        "Posted By":    "u/citizen_helper_guj",
        "District":     "State-wide",
        "Category":     "🏗️ Roads & Infrastructure",
        "Score":        2_341,
        "Comments":     289,
        "Sentiment":    "😊 Positive",
        "Top Comment":  "This should be pinned. Filed 3 complaints using this guide and all got resolved within 2 weeks!",
        "Date":         _date(7),
    },
    {
        "Post Title":   "AIIMS Rajkot update - what is the current status? Heard they're starting OPD",
        "Subreddit":    "r/rajkot",
        "Posted By":    "u/rajkot_health_watch",
        "District":     "Rajkot",
        "Category":     "🏥 Healthcare",
        "Score":        1_102,
        "Comments":     198,
        "Sentiment":    "😐 Neutral",
        "Top Comment":  "OPD started in limited departments. Cardiology and ortho running. Neurology still 3 months away.",
        "Date":         _date(5),
    },
    {
        "Post Title":   "Power cuts in Gandhinagar Sector 21 area - DGVCL ignoring complaints",
        "Subreddit":    "r/ahmedabad",
        "Posted By":    "u/gnr_sector21_res",
        "District":     "Gandhinagar",
        "Category":     "⚡ Electricity",
        "Score":        423,
        "Comments":     67,
        "Sentiment":    "😠 Negative",
        "Top Comment":  "Have been facing this since March. Escalated to consumer forum, no resolution yet.",
        "Date":         _date(4),
    },
    {
        "Post Title":   "Experience with Kisan Credit Card for tribal farmers in Dahod - sharing my journey",
        "Subreddit":    "r/gujarat",
        "Posted By":    "u/dahod_agri_voix",
        "District":     "Dahod",
        "Category":     "🌾 Agriculture",
        "Score":        1_876,
        "Comments":     312,
        "Sentiment":    "😊 Positive",
        "Top Comment":  "Very helpful. The bank officer in Limkheda branch is extremely supportive for tribal applicants.",
        "Date":         _date(9),
    },
    {
        "Post Title":   "Rant: Spent 6 hours at Vadodara Municipal for a simple birth certificate correction",
        "Subreddit":    "r/vadodara",
        "Posted By":    "u/baroda_bureaucracy",
        "District":     "Vadodara",
        "Category":     "📋 Land & Revenue",
        "Score":        3_241,
        "Comments":     445,
        "Sentiment":    "😠 Negative",
        "Top Comment":  "The e-Nagar app is supposed to handle this but the portal has been down for 2 weeks.",
        "Date":         _date(2),
    },
    {
        "Post Title":   "Gujarat's Swachh Bharat ranking 2025-26 - interesting district-wise breakdown",
        "Subreddit":    "r/india",
        "Posted By":    "u/data_india_analyst",
        "District":     "State-wide",
        "Category":     "🗑️ Sanitation & Waste",
        "Score":        987,
        "Comments":     143,
        "Sentiment":    "😐 Neutral",
        "Top Comment":  "Surat at top again but Dang and Tapi need serious attention in this data.",
        "Date":         _date(11),
    },
    {
        "Post Title":   "How I got my MGNREGA arrears cleared in 2 weeks - step by step",
        "Subreddit":    "r/gujarat",
        "Posted By":    "u/rural_rights_guj",
        "District":     "Narmada",
        "Category":     "👷 Employment/MGNREGA",
        "Score":        4_567,
        "Comments":     621,
        "Sentiment":    "😊 Positive",
        "Top Comment":  "This post literally got me my 8 months pending wages. Thank you so much. Please keep sharing.",
        "Date":         _date(14),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# 7. LOCAL MEDIA  (Gujarati / Regional news portals)
# ─────────────────────────────────────────────────────────────────────────────
LOCAL_MEDIA_SAMPLES = [
    {
        "Headline":     "ભાવનગરમાં 12 કિ.મી. ક્ષતિગ્રસ્ત ગ્રામ્ય રસ્તા: ગ્રામજનો ત્રાહિ ત્રાહિ",
        "Translation":  "12 km of damaged village roads in Bhavnagar: Villagers in distress",
        "Publication":  "Akila News",
        "Language":     "Gujarati",
        "District":     "Bhavnagar",
        "Category":     "🏗️ Roads & Infrastructure",
        "Sentiment":    "😠 Negative",
        "Date":         _date(3),
    },
    {
        "Headline":     "સુરત મ્યુ. ઇ-ગ્રિવન્સ પ્લેટફોર્મ: 30 દિવસમાં 94% ફરિયાદ નિવારણ",
        "Translation":  "Surat Municipal e-Grievance platform: 94% resolution within 30 days",
        "Publication":  "VTV Gujarati",
        "Language":     "Gujarati",
        "District":     "Surat",
        "Category":     "🏗️ Roads & Infrastructure",
        "Sentiment":    "😊 Positive",
        "Date":         _date(6),
    },
    {
        "Headline":     "Ahmedabad: AMTS bus overcrowding hits all-time high on 14 routes, passengers demand immediate relief",
        "Publication":  "Ahmedabad Mirror",
        "Language":     "English",
        "District":     "Ahmedabad",
        "Category":     "🏗️ Roads & Infrastructure",
        "Sentiment":    "😠 Negative",
        "Date":         _date(4),
    },
    {
        "Headline":     "ડાંગ જિલ્લામાં 23 ગ્રામ્ય સ્વાસ્થ્ય કેન્દ્ર ડૉક્ટર-વિહોણા: RTI ખુલાસો",
        "Translation":  "23 rural health centers in Dang district without doctors: RTI revelation",
        "Publication":  "Lok Sandesh",
        "Language":     "Gujarati",
        "District":     "Dang",
        "Category":     "🏥 Healthcare",
        "Sentiment":    "😠 Negative",
        "Date":         _date(8),
    },
    {
        "Headline":     "Kutch organic farmers earn 40% more via e-NAM digital mandi — success story",
        "Publication":  "Kutch Mitra",
        "Language":     "Gujarati",
        "District":     "Kutch",
        "Category":     "🌾 Agriculture",
        "Sentiment":    "😊 Positive",
        "Date":         _date(10),
    },
    {
        "Headline":     "Valsad: Industrialists slam illegal sand mining near Auranga river bank; demand police action",
        "Publication":  "Valsad Today",
        "Language":     "English",
        "District":     "Valsad",
        "Category":     "💰 Corruption/Bribery",
        "Sentiment":    "😠 Negative",
        "Date":         _date(5),
    },
    {
        "Headline":     "Gandhinagar 'Smart City' initiative gets 4-star rating in national urban index 2026",
        "Publication":  "Gujarat Guardian",
        "Language":     "English",
        "District":     "Gandhinagar",
        "Category":     "🏗️ Roads & Infrastructure",
        "Sentiment":    "😊 Positive",
        "Date":         _date(15),
    },
    {
        "Headline":     "Rajkot nagarpalika sanitation drive: 48 illegal dump yards cleared in 10 days",
        "Publication":  "Rajkot News Live",
        "Language":     "Gujarati",
        "District":     "Rajkot",
        "Category":     "🗑️ Sanitation & Waste",
        "Sentiment":    "😊 Positive",
        "Date":         _date(7),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Public API — all sources as a dict for easy iteration
# ─────────────────────────────────────────────────────────────────────────────
ALL_SOURCES = {
    "Twitter/X Social":  {"data": TWITTER_SAMPLES,  "color": "#1DA1F2", "icon": "🐦"},
    "PG Portal (Govt.)": {"data": PGPORTAL_SAMPLES,  "color": "#FF6B35", "icon": "🏛️"},
    "MyGov Portal":      {"data": MYGOV_SAMPLES,     "color": "#00BFA5", "icon": "🇮🇳"},
    "News Articles":     {"data": NEWS_SAMPLES,      "color": "#FF4081", "icon": "📰"},
    "RTI Filings":       {"data": RTI_SAMPLES,       "color": "#AB47BC", "icon": "📄"},
    "Reddit/Forums":     {"data": REDDIT_SAMPLES,    "color": "#FF7043", "icon": "💬"},
    "Local Media":       {"data": LOCAL_MEDIA_SAMPLES, "color": "#26C6DA", "icon": "📡"},
}
